config/routes.rb
Rails.application.routes.draw do

root "reports#index"
get "reports/" => "reports#index"
get "reports/new" => "reports#new", as: :new_report
get "reports/:id" => "reports#show", as: :report
post "reports/" => "reports#create"
get "reports/:id/edit" => "reports#edit", as: :edit_report
patch "reports/:id" => "reports#update"
delete "reports/:id" => "reports#destroy"

get "tutors" => "tutors#index"
post "tutors" => "tutors#create"
get "signup" => "tutors#new"

get "/login" => "sessions#new"
post "/login" => "sessions#create"
delete "/logout" => "sessions#destroy"

end

app/models/report.rb
class Report < ActiveRecord::Base

	belongs_to :tutor

end

app/models/tutor.rb
class Tutor < ActiveRecord::Base
	
	attr_reader :password
	
	has_many :reports

	def password=(unencrypted_password)
		unless unencrypted_password.empty?
			@password = unencrypted_password
			self.password_digest = BCrypt::Password.create(unencrypted_password)
		end
	end
	def authenticate(unencrypted_password)
		if BCrypt::Password.new(self.password_digest) == unencrypted_password
			return self
		else
			return false
		end
	end
end #end of the class

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

helper_method :current_tutor

private
def current_tutor
	@current_tutor ||=Tutor.find(session[:tutor_id]) if session[:tutor_id]
end

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController

	def index
		@reports = Report.all
	end

	def show
		@report = Report.find(params[:id])
	end

	def new
		@report = Report.new
	end

	def create
		@report = Report.new(report_params)
		
		# if @report.save
		# flash[:notice] = 'New report created.'
  #   # redirect_to(:action => 'index')

		# #if @report.save
		# 	#redirect_to reports_path #need to be able to give a message saying report saved.  
		# else
			@report.save
			render :new
		# end
	end

	def edit
		@report = Report.find(params[:id])
	end

	def update
		@report = Report.find(params[:id])

		if @report.update_attributes(report_params)
			redirect_to reports_path
		else
			render :edit
		end
	end

	def destroy
		@report = Report.find(params[:id])
		@report.destroy
		redirect_to reports_path
	end

	private
	def report_params
		params.require(:report).permit(:student_id, :teacher_id, :what_was_covered, 
			:performance, :assignment)
	end

end #end of controller

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end
	def create
		tutor = Tutor.where(email: params[:login][:email]).first
		if tutor && tutor.authenticate(params[:login][:password])
			session[:tutor_id] = tutor.id.to_s
			redirect_to new_report_path
		else
			redirect_to login_path
		end
	end

	def destroy
		session.delete(:tutor_id)
		redirect_to login_path
	end
end #end of controller

app/controllers/tutors_controller.rb
class TutorsController < ApplicationController

	def index
		@tutors = Tutor.all
	end

	def new
		@tutor = Tutor.new
	end

	def create
		@tutor = Tutor.new(tutor_params)
		if @tutor.save
			redirect_to tutors_path
		else	
			render :new
		end
	end

private

	def tutor_params
		params.require(:tutor).permit(:name, :email, :password)
	end
end #end of controller

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
def logged_in?
  session[:tutor_id] != nil
end
end

app/helpers/tutors_helper.rb
module TutorsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TutorSessions</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

<%= yield %>

</body>
</html>

app/views/reports/edit.html.erb
<% if logged_in? %>    

    <h1>Edit a Report</h1>

    <%= form_for @report do |f| %>

        <div>
            <%= f.label :student_id %>
            <%= f.text_field :student_id %>
        </div>

        <div>
            <%= f.label :teacher_id %>
            <%= f.text_field :teacher_id %>
        </div>

        <div>
            <%= f.label :what_was_covered %>
            <%= f.text_area :what_was_covered %>
        </div>

        <div>
            <%= f.label :performance %>
            <%= f.text_area :performance %>
        </div>

        <div>
            <%= f.label :assignment %>
            <%= f.text_area :assignment %>
        </div>
        <br>
        <%= f.submit "Submit these changes" %>

    <% end %>
    <br>
    <%= link_to "Back to your reports", reports_path %>
    <br>
  Logged in as: <%= current_tutor.name %> <br><br> <%= link_to 'Log Out', logout_path, method: :delete %>

<% else %>
  <h1>You are not logged in.  Please log in to access this page.</h1>
  <%= link_to 'Log In', login_path %>
<% end %>   

app/views/reports/index.html.erb
<% if logged_in? %>	

	<div class="container-fluid">

	<div class="jumbotron">
	<div class="masthead">
		<h1>Your Reports:<h1>
	</div>
	<!-- <img src="assets/logo_4NF.jpg" alt="Responsive image" class="img-rounded"> -->
	<%= image_tag "logo_4NF.jpg" %>
	<ol>
		<% @reports.each do |report| %>
			<li>
				Student ID #<%= report.student_id %> 
				<%= link_to "Access full report", report_path(report) %>
			</li>
		<% end %>
	</ol>
	</div>
	<%= link_to "Create a new report", new_report_path %>

	<!-- need to figure out how to have this page show only today's reports -->
	</div>
	Logged in as: <%= current_tutor.name %> <br><br> <%= link_to 'Log Out', logout_path, method: :delete %>

	<% else %>
	 <h1>You are not logged in.  Please log in to access this page.</h1>
  <%= link_to 'Log In', login_path %>
<% end %>

app/views/reports/new.html.erb
<% if logged_in? %>
  
  <h1>Add a new report</h1>

    <%= form_for @report do |f| %>
      <div>
          <%= f.label :student_id %>
          <%= f.text_field :student_id %>
      </div>

      <div>
          <%= f.label :teacher_id %>
          <%= f.text_field :teacher_id %>
      </div>

      <div>
          <%= f.label :what_was_covered %>
          <%= f.text_area :what_was_covered %>
      </div>

      <div>
          <%= f.label :performance %>
          <%= f.text_area :performance %>
      </div>

      <div>
          <%= f.label :assignment %>
          <%= f.text_area :assignment %>
      </div>
      <br>
    <%= f.submit "Add new report" %>

    <% end %>
    <br>
    <%= link_to "Go to your reports", reports_path %>
    <br>
    <br>
    
    Logged in as: <%= current_tutor.name %> <br><br> <%= link_to 'Log Out', logout_path, method: :delete %>

<% else %>
  <h1>You are not logged in.  Please log in to access this page.</h1>
  <%= link_to 'Log In', login_path %>
<% end %>

app/views/reports/show.html.erb
<% if logged_in? %>
	<h1> <%= @report.student_id %> </h1>

	<p>What was covered: <br> <%= @report.what_was_covered%>  <br><br>Performance: <br> <%= @report.performance%> <br><br> Assignment: <br> <%= @report.assignment %><br><br>

	<%= link_to "Back to today's Report list", reports_path %> <br> <br>
	<%= link_to "Edit this report", edit_report_path(@report) %>
	<br> <br>
	<%= link_to "Delete this report", report_path, method: :delete, data: {confirm: "Are you sure you want to delete this report?"} %> 

	<br> 
	<br>

	<%= link_to "Create a new report", new_report_path %>
	<br>
	Logged in as: <%= current_tutor.name %> <br><br> <%= link_to 'Log Out', logout_path, method: :delete %>

	<% else %>
	  <h1>You are not logged in.  Please log in to access this page.</h1>
	  <%= link_to 'Log In', login_path %>
<% end %>

app/views/tutors/index.html.erb
<h1>Tutors</h1>
<% if logged_in? %>
  Logged in as: <%= current_tutor.name %> 

	<ul>
		<% @tutors.each do |tutor| %> 
		<li><%= tutor.name %></li>
	<% end %>
	</ul>

  <%= link_to 'Log Out', logout_path, method: :delete %>
<% else %>
  <%= link_to 'Log In', login_path %>
<% end %>

app/views/tutors/new.html.erb
<!-- Need an access key for tutors to sign up -->
	<h1>Sign Up</h1>
	<%= form_for @tutor do |f| %>
		<div>
			<%= f.label :name %>
			<%= f.text_field :name %>
		</div>
		<div>
			<%= f.label :email %>
			<%= f.text_field :email %>
		</div>
		<div>
			<%= f.label :password %>
			<%= f.password_field :password %>
		</div>
		<div>
			<%= f.submit %>
		</div>
	<% end %>